/**
 * Fetch Google Fonts as self-hosted WOFF2 files.
 * Runs before every build. Falls back to existing files if fetch fails.
 *
 * Config: edit the FONTS array below to change families/weights.
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const FONTS_DIR = join(ROOT, 'public', 'fonts');
const CSS_OUTPUT = join(ROOT, 'src', 'styles', 'fonts.css');

// ---- Font configuration ----
const FONTS = [
  { family: 'DM Sans', weights: '400;500;700', cssFamily: "'DM Sans'" },
  { family: 'Syne', weights: '700;800', cssFamily: "'Syne'" },
];

const CHROME_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function fetchGoogleCSS() {
  const families = FONTS.map(f => `family=${f.family.replace(/ /g, '+')}:wght@${f.weights}`).join('&');
  const url = `https://fonts.googleapis.com/css2?${families}&display=swap`;

  const res = await fetch(url, { headers: { 'User-Agent': CHROME_UA } });
  if (!res.ok) throw new Error(`Google Fonts API returned ${res.status}`);
  return res.text();
}

function parseFontFaces(css) {
  const faces = [];
  const regex = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let match;

  while ((match = regex.exec(css)) !== null) {
    const subset = match[1]; // e.g. "latin", "latin-ext"
    const block = match[2];

    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const srcUrl = block.match(/url\(([^)]+)\)/)?.[1];
    const unicodeRange = block.match(/unicode-range:\s*([^;]+)/)?.[1]?.trim();

    if (family && weight && srcUrl && unicodeRange) {
      faces.push({ family, weight, subset, srcUrl, unicodeRange });
    }
  }
  return faces;
}

function buildFilename(family, subset) {
  return `${family.toLowerCase().replace(/ /g, '-')}-${subset}.woff2`;
}

async function downloadFont(url, destPath) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  writeFileSync(destPath, buffer);
}

function generateCSS(faces, fileMap) {
  // Group by family+subset (since all weights share the same file with variable fonts)
  const groups = new Map();
  for (const face of faces) {
    const key = `${face.family}|${face.subset}`;
    if (!groups.has(key)) {
      groups.set(key, { ...face, weights: [face.weight] });
    } else {
      groups.get(key).weights.push(face.weight);
    }
  }

  let css = '/* Auto-generated by scripts/fetch-fonts.mjs — do not edit manually */\n\n';

  for (const [, group] of groups) {
    const filename = buildFilename(group.family, group.subset);
    const minWeight = Math.min(...group.weights.map(Number));
    const maxWeight = Math.max(...group.weights.map(Number));
    const weightRange = minWeight === maxWeight ? minWeight : `${minWeight} ${maxWeight}`;

    css += `/* ${group.family} — ${group.subset} */\n`;
    css += `@font-face {\n`;
    css += `  font-family: '${group.family}';\n`;
    css += `  font-style: normal;\n`;
    css += `  font-weight: ${weightRange};\n`;
    css += `  font-display: swap;\n`;
    css += `  src: url('/fonts/${filename}') format('woff2');\n`;
    css += `  unicode-range: ${group.unicodeRange};\n`;
    css += `}\n\n`;
  }

  return css;
}

async function main() {
  console.log('[fonts] Fetching Google Fonts CSS...');

  let css;
  try {
    css = await fetchGoogleCSS();
  } catch (err) {
    console.warn(`[fonts] Fetch failed: ${err.message}`);
    if (existsSync(CSS_OUTPUT)) {
      console.log('[fonts] Using existing fonts as fallback.');
      return;
    }
    throw new Error('[fonts] No fallback fonts available. Build cannot continue.');
  }

  const faces = parseFontFaces(css);
  if (faces.length === 0) {
    console.warn('[fonts] No font faces parsed. Using existing fonts as fallback.');
    return;
  }

  console.log(`[fonts] Found ${faces.length} font faces. Downloading WOFF2 files...`);

  mkdirSync(FONTS_DIR, { recursive: true });

  // Dedupe downloads (same file for multiple weights with variable fonts)
  const downloaded = new Set();
  for (const face of faces) {
    const filename = buildFilename(face.family, face.subset);
    if (downloaded.has(filename)) continue;
    downloaded.add(filename);

    const destPath = join(FONTS_DIR, filename);
    try {
      await downloadFont(face.srcUrl, destPath);
      console.log(`[fonts]   ✓ ${filename}`);
    } catch (err) {
      console.warn(`[fonts]   ✗ ${filename}: ${err.message}`);
      if (existsSync(destPath)) {
        console.log(`[fonts]     Using existing file as fallback.`);
      }
    }
  }

  // Generate CSS
  const generatedCSS = generateCSS(faces);
  writeFileSync(CSS_OUTPUT, generatedCSS);
  console.log(`[fonts] Generated ${CSS_OUTPUT.replace(ROOT, '')}`);
  console.log('[fonts] Done.');
}

main().catch(err => {
  console.error(err.message);
  process.exit(1);
});
